topics:
- name    : pad_unsafe
  topic   : pad_teleop/unsafe/cmd_vel # UNSAFE
  timeout : 0.5
  priority: 100

- name    : safe_command
  topic   : rough_terrain_navigation/pad_teleop/cmd_vel # SAFE
  timeout : 0.5
  priority: 75

- name    : move_base
  topic   : rough_terrain_navigation/move_base/cmd_vel
  timeout : 0.5
  priority: 50

- name    : docker
  topic   : docker/cmd_vel
  timeout : 0.5
  priority: 50

- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1

locks:
- name    : e_stop
  topic   : robotnik_base_hw/emergency_stop
  timeout : 0.0
  priority: 255
