local_costmap:
  global_frame: $(arg odom_frame)
  robot_base_frame: $(arg base_frame)
  update_frequency: 5.0
  static_map: true
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: static_map
      type: "costmap_2d::StaticLayer"
    - name: obstacle_laser_layer
      type: "costmap_2d::ObstacleLayer"
#    - name: obstacle_camera_layer
#      type: "costmap_2d::VoxelLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  static_map:
    enabled: true
    lethal_cost_threshold: 94
    static_map: true
    map_topic: "/map"
    unknown_cost_value: -1
    trinary_costmap: false
    use_maximum: false
    first_map_only: false
